langugage: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17



env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8


# before_install:
#  - cd $HOME
#  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O $HOME/android-sdk.tgz
#  - mkdir android
#  - unzip android-sdk.tgz -d android/sdk
#  - export PATH=$PATH:$HOME/android/sdk/tools:$HOME/android/sdk/tools/bin
#  - cd build/


before_install:
  - chmod +x gradlew

script:
  #- ./gradlew clean assembleDebug assembleRelease testDebug
  - ./gradlew build --stacktrace
