langugage: android
android:
  components:
    - android-28
    - build-tools-27.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
